Docs: add descriptions to chat/callsign filter
BZFlag-Dev/bzflag.org pull request #41
Opened 2021-05-28 01:58 UTC by RighthandSon

Adds descriptions for `bz_CallsignsFiltered`, `bz_ChatFiltered`, and `bz_SetFiltering`.

2021-05-29 09:05 UTC, allejo requested changes
I'd specify the respect BZFS options that these functions are tied to and also link to the API function that allows you to change said options.

2021-05-29 09:05 UTC, allejo commented on _documentation/developer/bzfs_api_functions/bz_CallsignsFiltered.md
> +Check if Callsigns are being filtered.
```suggestion
Check if callsigns are being filtered. This is tied to the `-filterCallsigns` server option or to server settings set via [`bz_SetFiltering`]({{ url(collections.bzfs_api_functions['bz_SetFiltering']) }}).
```

2021-05-29 09:05 UTC, allejo commented on _documentation/developer/bzfs_api_functions/bz_ChatFiltered.md
> +Checks if chat is being fitered.
```suggestion
Checks if chat is being fitered. This is tied to the `-filterChat` server option or to server settings set via [`bz_SetFiltering`]({{ url(collections.bzfs_api_functions['bz_SetFiltering']) }}).
```

2021-05-30 06:07 UTC, jwmelto approved these changes

2021-05-31 22:38 UTC, allejo approved these changes

2021-05-31 22:39 UTC, merged